[package]
name = "ip-scanner"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.23.0", features = ["full"] }
bpaf = { version = "0.7.7", features = ["derive", "bright-color"] }